@startuml
actor  Usuario 
agent ClientPresentation #Violet
agent CommandHandlersClient #Orange
agent CommandHandlersServer  #Violet
cloud "Red (TCP y Protocolo)" as Red
database DataAccess 
agent BusinessLogic  #Orange


Usuario -up-> ClientPresentation: 1
ClientPresentation -down-> Usuario : 12

ClientPresentation -up-> CommandHandlersClient: 2
CommandHandlersClient -down-> ClientPresentation : 11 ServerError

CommandHandlersClient -right-> Red: 3
Red -left-> CommandHandlersClient : 10 Command.Error
Red -right-> CommandHandlersServer: 4
CommandHandlersServer -left-> Red : 9 Command.Error

CommandHandlersServer -down-> BusinessLogic: 5
BusinessLogic -up-> CommandHandlersServer : 8 ServerError

BusinessLogic -down-> DataAccess: 6
DataAccess -up-> BusinessLogic : 7

/'one -right-> two: message 1-->2
two -right-> three: message 2-->3
two --> four: message 2-->4
three -[hidden]- four'/
@enduml